"""create initial schema

Revision ID: 4dfe3e5cd4e7
Revises: 
Create Date: 2026-08-25 15:11:10.215882

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4dfe3e5cd4e7'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categories',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id', name='pk_categories'),
    sa.UniqueConstraint('name', name='uq_categories_name')
    )
    op.create_table('permissions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('key', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id', name='pk_permissions'),
    sa.UniqueConstraint('key', name='uq_permissions_key')
    )
    op.create_table('roles',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id', name='pk_roles'),
    sa.UniqueConstraint('name', name='uq_roles_name')
    )
    op.create_table('tags',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id', name='pk_tags'),
    sa.UniqueConstraint('name', name='uq_tags_name')
    )
    op.create_table('role_permissions',
    sa.Column('role_id', sa.Uuid(), nullable=False),
    sa.Column('permission_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['permission_id'], ['permissions.id'], name='fk_role_permissions_permission_id_permissions', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], name='fk_role_permissions_role_id_roles', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('role_id', 'permission_id', name='pk_role_permissions')
    )
    op.create_table('users',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role_id', sa.Uuid(), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], name='fk_users_role_id_roles', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name='pk_users'),
    sa.UniqueConstraint('email', name='uq_users_email')
    )
    op.create_table('events',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('organizer_id', sa.Uuid(), nullable=False),
    sa.Column('category_id', sa.Uuid(), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('venue', sa.String(length=255), nullable=False),
    sa.Column('event_datetime', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ticket_price', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('total_tickets', sa.Integer(), nullable=False),
    sa.Column('tickets_available', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('draft', 'published', 'cancelled', 'completed', name='ck_events_event_status', native_enum=False, create_constraint=True), server_default='draft', nullable=False),
    sa.Column('reminder_sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint('ticket_price >= 0', name='ck_events_ticket_price_non_negative'),
    sa.CheckConstraint('tickets_available <= total_tickets', name='ck_events_tickets_available_within_capacity'),
    sa.CheckConstraint('tickets_available >= 0', name='ck_events_tickets_available_non_negative'),
    sa.CheckConstraint('total_tickets >= 0', name='ck_events_total_tickets_non_negative'),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], name='fk_events_category_id_categories', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['organizer_id'], ['users.id'], name='fk_events_organizer_id_users', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name='pk_events')
    )
    op.create_table('logs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('actor_id', sa.Uuid(), nullable=True),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('entity_type', sa.String(length=100), nullable=False),
    sa.Column('entity_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['actor_id'], ['users.id'], name='fk_logs_actor_id_users', ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name='pk_logs')
    )
    op.create_table('refresh_tokens',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('token_hash', sa.String(length=128), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('expires_at > created_at', name='ck_refresh_tokens_expiry_after_creation'),
    sa.CheckConstraint('revoked_at IS NULL OR revoked_at >= created_at', name='ck_refresh_tokens_revocation_not_before_creation'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='fk_refresh_tokens_user_id_users', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='pk_refresh_tokens'),
    sa.UniqueConstraint('token_hash', name='uq_refresh_tokens_token_hash')
    )
    op.create_table('bookings',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('event_id', sa.Uuid(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('confirmed', 'cancelled', name='ck_bookings_booking_status', native_enum=False, create_constraint=True), server_default='confirmed', nullable=False),
    sa.Column('booked_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('cancelled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("(status = 'confirmed' AND cancelled_at IS NULL) OR (status = 'cancelled' AND cancelled_at IS NOT NULL)", name='ck_bookings_status_matches_cancellation_time'),
    sa.CheckConstraint('quantity > 0', name='ck_bookings_quantity_positive'),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], name='fk_bookings_event_id_events', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='fk_bookings_user_id_users', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name='pk_bookings')
    )
    op.create_table('event_tags',
    sa.Column('event_id', sa.Uuid(), nullable=False),
    sa.Column('tag_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], name='fk_event_tags_event_id_events', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tag_id'], ['tags.id'], name='fk_event_tags_tag_id_tags', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('event_id', 'tag_id', name='pk_event_tags')
    )
    op.create_table('reviews',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('event_id', sa.Uuid(), nullable=False),
    sa.Column('rating', sa.Integer(), nullable=False),
    sa.Column('comment', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('rating BETWEEN 1 AND 5', name='ck_reviews_rating_between_one_and_five'),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], name='fk_reviews_event_id_events', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='fk_reviews_user_id_users', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name='pk_reviews'),
    sa.UniqueConstraint('user_id', 'event_id', name='uq_reviews_user_id_event_id')
    )
    op.create_table('notifications',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('related_event_id', sa.Uuid(), nullable=True),
    sa.Column('related_booking_id', sa.Uuid(), nullable=True),
    sa.Column('related_review_id', sa.Uuid(), nullable=True),
    sa.Column('read_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('(CASE WHEN related_event_id IS NULL THEN 0 ELSE 1 END + CASE WHEN related_booking_id IS NULL THEN 0 ELSE 1 END + CASE WHEN related_review_id IS NULL THEN 0 ELSE 1 END) <= 1', name='ck_notifications_at_most_one_related_entity'),
    sa.ForeignKeyConstraint(['related_booking_id'], ['bookings.id'], name='fk_notifications_related_booking_id_bookings', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['related_event_id'], ['events.id'], name='fk_notifications_related_event_id_events', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['related_review_id'], ['reviews.id'], name='fk_notifications_related_review_id_reviews', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='fk_notifications_user_id_users', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='pk_notifications')
    )
    op.create_table('replies',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('review_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['review_id'], ['reviews.id'], name='fk_replies_review_id_reviews', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='fk_replies_user_id_users', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name='pk_replies')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('replies')
    op.drop_table('notifications')
    op.drop_table('reviews')
    op.drop_table('event_tags')
    op.drop_table('bookings')
    op.drop_table('refresh_tokens')
    op.drop_table('logs')
    op.drop_table('events')
    op.drop_table('users')
    op.drop_table('role_permissions')
    op.drop_table('tags')
    op.drop_table('roles')
    op.drop_table('permissions')
    op.drop_table('categories')
    # ### end Alembic commands ###
