"""align models with updated erd

Revision ID: d8425bcacf7f
Revises: 4dfe3e5cd4e7
Create Date: 2026-08-27 16:13:49.805982

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd8425bcacf7f'
down_revision: Union[str, Sequence[str], None] = '4dfe3e5cd4e7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_bookings_user_id_event_id', 'bookings', ['user_id', 'event_id'])
    op.drop_column('bookings', 'deleted_at')
    op.alter_column('events', 'ticket_price',
               existing_type=sa.NUMERIC(precision=12, scale=2),
               type_=sa.Numeric(precision=10, scale=2),
               existing_nullable=False)
    op.drop_constraint('ck_notifications_at_most_one_related_entity', 'notifications', type_='check')
    op.drop_constraint(op.f('fk_notifications_related_event_id_events'), 'notifications', type_='foreignkey')
    op.drop_column('notifications', 'related_event_id')
    op.create_check_constraint(
        'ck_notifications_at_most_one_related_entity',
        'notifications',
        '(CASE WHEN related_booking_id IS NULL THEN 0 ELSE 1 END + '
        'CASE WHEN related_review_id IS NULL THEN 0 ELSE 1 END) <= 1',
    )
    op.add_column('replies', sa.Column('replier_role', sa.Enum('organizer', 'admin', name='ck_replies_replier_role', native_enum=False, create_constraint=True), nullable=False))
    op.create_unique_constraint('uq_replies_review_id_replier_role', 'replies', ['review_id', 'replier_role'])
    op.create_unique_constraint('uq_replies_review_id_user_id', 'replies', ['review_id', 'user_id'])
    op.add_column('reviews', sa.Column('booking_id', sa.Uuid(), nullable=False))
    op.drop_constraint(op.f('uq_reviews_user_id_event_id'), 'reviews', type_='unique')
    op.create_unique_constraint('uq_reviews_booking_id', 'reviews', ['booking_id'])
    op.drop_constraint(op.f('fk_reviews_event_id_events'), 'reviews', type_='foreignkey')
    op.drop_constraint(op.f('fk_reviews_user_id_users'), 'reviews', type_='foreignkey')
    op.create_foreign_key('fk_reviews_booking_id_bookings', 'reviews', 'bookings', ['booking_id'], ['id'], ondelete='RESTRICT')
    op.drop_column('reviews', 'event_id')
    op.drop_column('reviews', 'user_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reviews', sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=True))
    op.add_column('reviews', sa.Column('event_id', sa.UUID(), autoincrement=False, nullable=True))
    op.execute(
        sa.text(
            'UPDATE reviews AS review '
            'SET user_id = booking.user_id, event_id = booking.event_id '
            'FROM bookings AS booking '
            'WHERE review.booking_id = booking.id'
        )
    )
    op.alter_column('reviews', 'user_id', nullable=False)
    op.alter_column('reviews', 'event_id', nullable=False)
    op.drop_constraint('fk_reviews_booking_id_bookings', 'reviews', type_='foreignkey')
    op.create_foreign_key(op.f('fk_reviews_user_id_users'), 'reviews', 'users', ['user_id'], ['id'], ondelete='RESTRICT')
    op.create_foreign_key(op.f('fk_reviews_event_id_events'), 'reviews', 'events', ['event_id'], ['id'], ondelete='RESTRICT')
    op.drop_constraint('uq_reviews_booking_id', 'reviews', type_='unique')
    op.create_unique_constraint(op.f('uq_reviews_user_id_event_id'), 'reviews', ['user_id', 'event_id'], postgresql_nulls_not_distinct=False)
    op.drop_column('reviews', 'booking_id')
    op.drop_constraint('uq_replies_review_id_user_id', 'replies', type_='unique')
    op.drop_constraint('uq_replies_review_id_replier_role', 'replies', type_='unique')
    op.drop_constraint('ck_replies_replier_role', 'replies', type_='check')
    op.drop_column('replies', 'replier_role')
    op.drop_constraint('ck_notifications_at_most_one_related_entity', 'notifications', type_='check')
    op.add_column('notifications', sa.Column('related_event_id', sa.UUID(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('fk_notifications_related_event_id_events'), 'notifications', 'events', ['related_event_id'], ['id'], ondelete='SET NULL')
    op.create_check_constraint(
        'ck_notifications_at_most_one_related_entity',
        'notifications',
        '(CASE WHEN related_event_id IS NULL THEN 0 ELSE 1 END + '
        'CASE WHEN related_booking_id IS NULL THEN 0 ELSE 1 END + '
        'CASE WHEN related_review_id IS NULL THEN 0 ELSE 1 END) <= 1',
    )
    op.alter_column('events', 'ticket_price',
               existing_type=sa.Numeric(precision=10, scale=2),
               type_=sa.NUMERIC(precision=12, scale=2),
               existing_nullable=False)
    op.add_column('bookings', sa.Column('deleted_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.drop_constraint('uq_bookings_user_id_event_id', 'bookings', type_='unique')
    # ### end Alembic commands ###
