UPDATE_OWN_PROFILE = "profile.update_own"
CHANGE_OWN_PASSWORD = "password.change_own"

VIEW_ALL_USERS = "users.view_all"
CHANGE_USER_ROLE = "users.change_role"
CHANGE_USER_STATUS = "users.change_status"

CREATE_EVENTS = "events.create"
EDIT_ANY_EVENT = "events.edit_any"
EDIT_OWN_EVENT = "events.edit_own"
CANCEL_ANY_EVENT = "events.cancel_any"
CANCEL_OWN_EVENT = "events.cancel_own"
VIEW_PUBLISHED_EVENTS = "events.view_published"

CREATE_BOOKINGS = "bookings.create"
CANCEL_ANY_BOOKING = "bookings.cancel_any"
CANCEL_OWN_BOOKING = "bookings.cancel_own"
VIEW_OWN_BOOKINGS = "bookings.view_own"

CREATE_REVIEWS = "reviews.create"
REPLY_TO_ANY_REVIEW = "reviews.reply_any"
REPLY_TO_OWN_EVENT_REVIEWS = "reviews.reply_own_events"
EDIT_OWN_REVIEW = "reviews.edit_own"
DELETE_OWN_REVIEW = "reviews.delete_own"
EDIT_ANY_REVIEW = "reviews.edit_any"
DELETE_ANY_REVIEW = "reviews.delete_any"

VIEW_OWN_NOTIFICATIONS = "notifications.view_own"
VIEW_AUDIT_LOGS = "logs.view"

READ_CATEGORIES = "categories.read"
CREATE_CATEGORIES = "categories.create"
DELETE_CATEGORIES = "categories.delete"
READ_TAGS = "tags.read"
CREATE_TAGS = "tags.create"
DELETE_TAGS = "tags.delete"
